version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      target: development
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_WS_API_URL=http://localhost:8000
      - VITE_AUTHORIZATION_SESSION=HANDY_KEY
      - VITE_BACKEND_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      target: development
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/one
      - JWT_SECRET_KEY=H@ndyP0pul4rN3tw0rkT3chn0l0gy2024S3cr3tK3y!
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - app-network
      - db-network
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npm run migrate:dev && npm run start:dev"
    restart: unless-stopped

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=one
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - db-network
    depends_on:
      - db
    restart: unless-stopped

  prisma-studio:
    build:
      context: ./backend
      target: development
    ports:
      - "5555:5555" 
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/one
    networks:
      - db-network
    depends_on:
      db:
        condition: service_healthy
    command: npx prisma studio --port 5555 --hostname 0.0.0.0
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:

networks:
  app-network:
    driver: bridge
  db-network:
    driver: bridge